### ISSUE TITLE
Problems getting Harmony Ganache Running On OSX

### ISSUE THREAD

**Issue by devonartis** [harmony-one/harmony-one-ganache-support#1]
I attempted to install Harmony Ganache based on the documentation provided 

### First Step 
`git clone --recursive https://github.com/harmony-one/harmony-one-ganache-support
cd harmony-one-ganache-support`

### Second Step

**_You can download a self-contained prebuilt Ganache with Harmony One support binary for your platform of choice from this repository's releases page._** 
`./ganache-2.6.0-beta.3-linux-x86_64.AppImage`

I could not find a ./ganache-2.6.0-beta.3-linux-x86_64.AppImage and when I clicked on this link [releases ](https://github.com/harmony-one/harmony-one-ganache-support/releases)as stated in the documentation it did not have an .AppImage.

### Third Step

Download the software from [releases ](https://github.com/harmony-one/harmony-one-ganache-support/releases) and follow the instruction on buildinging .AppImage or .dmg from [Harmony Integration](https://github.com/GabrielNicolasAvellaneda/ganache/tree/harmony-integration)

Additionally other users are having problems but did not go into much details 

**_Taken From Dev Community Group_**
![image](https://user-images.githubusercontent.com/4836786/123843106-85430280-d8df-11eb-8e96-669f439d46c0.png)

Taken From Harmony Devs Reddit 
[Local Blockchain Issues](https://www.reddit.com/r/Harmony_Devs/comments/o98lxv/local_blockchain/?utm_source=share&utm_medium=web2x&context=3)
![image](https://user-images.githubusercontent.com/4836786/123843177-9ab82c80-d8df-11eb-85c4-25470926a345.png)

**Comment by Severino** [comment]
What error do you get? I can start the application, but when starting the harmony-one network, I get this error:

docker run --name harmony-localnet-ganache --rm -d -p 9500:9500 -p 9800:9800 -p 9801:9801 -p 9501:9501 harmonyone/localnet-ganache
Unable to find image ‘harmonyone/localnet-ganache:latest’ locally

The created image is named ‘harmonyone/localnet-test’, maybe it's a naming issue.
I have described my problems here in further detail: 
https://talk.harmony.one/t/thread-technical-feedback/1454/3?u=severin

**Comment by devonartis** [comment]
@Severino I am just going through the documentation on our site I did not see any directions to use docker although I did see the docker directory and the docker file. I also was not able to find ./ganache-harmony/dist/ganache-2.6.0-beta.3-linux-x86_64.AppImage where you able to find it. 

It has been updated with ganache-2.6.0-beta.3-linux-x86_64.AppImage but it's not really clear what you should be doing to get ganache up and running.

**Comment by devonartis** [comment]
Closing this issue as I will open up issues regarding to windows and osx.
